# Generated by Django 3.2.21 on 2023-09-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_code',
            new_name='discount',
        ),
    ]
