# Generated by Django 3.2.21 on 2023-09-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_rename_discount_code_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
