# Generated by Django 3.2.21 on 2023-09-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230921_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
