# Generated by Django 3.2.21 on 2023-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230921_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
